export const stations = [
    { id: 1, name: "Connaught Place" },
    { id: 2, name: "India Gate" },
    { id: 3, name: "Chandni Chowk" },
    { id: 4, name: "Lajpat Nagar" },
    { id: 5, name: "Karol Bagh" },
    { id: 6, name: "Nehru Place" },
    { id: 7, name: "Saket" },
    { id: 8, name: "Dwarka" },
    { id: 9, name: "Rohini" },
    { id: 10, name: "Janakpuri" },
    { id: 11, name: "Vasant Kunj" },
    { id: 12, name: "Hauz Khas" },
    { id: 13, name: "Pitampura" },
    { id: 14, name: "Rajouri Garden" },
    { id: 15, name: "Shahdara" },
    { id: 16, name: "Mayur Vihar" },
    { id: 17, name: "Sarita Vihar" },
    { id: 18, name: "Badarpur" },
    { id: 19, name: "Kashmere Gate" },
    { id: 20, name: "Yamuna Bank" },
];

export const buses = [
    {
        id: 1,
        number: "DTC 423",
        fare: 30,
        crowdLevel: "Medium",
        fullness: 65,
        arrivalTime: "3 min",
        color: "bg-blue-500",
        route: [
            { stop: "Connaught Place", visited: true },
            { stop: "Mandi House", visited: true },
            { stop: "Pragati Maidan", visited: false },
            { stop: "ITO", visited: false },
            { stop: "Delhi Gate", visited: false },
            { stop: "Jama Masjid", visited: false },
        ],
        routeProgress: 33,
        reviews: [
            { rating: 4, comment: "Clean and usually on time" },
            { rating: 3, comment: "Can get crowded during peak hours" },
        ],
    },
    {
        id: 2,
        number: "DTC 581",
        fare: 25,
        crowdLevel: "Low",
        fullness: 40,
        arrivalTime: "7 min",
        color: "bg-green-500",
        route: [
            { stop: "India Gate", visited: true },
            { stop: "Udyog Bhawan", visited: true },
            { stop: "Patel Chowk", visited: true },
            { stop: "Central Secretariat", visited: false },
            { stop: "Janpath", visited: false },
        ],
        routeProgress: 60,
        reviews: [
            { rating: 5, comment: "Very comfortable ride" },
            { rating: 4, comment: "Friendly driver" },
        ],
    },
    {
        id: 3,
        number: "DTC 724",
        fare: 35,
        crowdLevel: "High",
        fullness: 90,
        arrivalTime: "1 min",
        color: "bg-red-500",
        route: [
            { stop: "Chandni Chowk", visited: true },
            { stop: "Chawri Bazar", visited: true },
            { stop: "New Delhi", visited: false },
            { stop: "Rajiv Chowk", visited: false },
            { stop: "Barakhamba Road", visited: false },
        ],
        routeProgress: 40,
        reviews: [
            { rating: 2, comment: "Always packed, needs more frequent service" },
            { rating: 3, comment: "Punctual but uncomfortable during rush hour" },
        ],
    },
    {
        id: 4,
        number: "DTC 340",
        fare: 20,
        crowdLevel: "Medium",
        fullness: 70,
        arrivalTime: "5 min",
        color: "bg-yellow-500",
        route: [
            { stop: "Lajpat Nagar", visited: true },
            { stop: "Moolchand", visited: true },
            { stop: "Defence Colony", visited: false },
            { stop: "AIIMS", visited: false },
            { stop: "Green Park", visited: false },
        ],
        routeProgress: 40,
        reviews: [
            { rating: 4, comment: "Good connectivity to major areas" },
            { rating: 3, comment: "Decent service, could be cleaner" },
        ],
    },
    {
        id: 5,
        number: "DTC 501",
        fare: 28,
        crowdLevel: "Low",
        fullness: 50,
        arrivalTime: "6 min",
        color: "bg-purple-500",
        route: [
            { stop: "Karol Bagh", visited: true },
            { stop: "Rajendra Place", visited: true },
            { stop: "Patel Nagar", visited: false },
            { stop: "Shadipur", visited: false },
            { stop: "Kirti Nagar", visited: false },
        ],
        routeProgress: 40,
        reviews: [
            { rating: 5, comment: "Comfortable and clean" },
            { rating: 4, comment: "Good service" },
        ],
    },
    {
        id: 6,
        number: "DTC 602",
        fare: 22,
        crowdLevel: "Medium",
        fullness: 60,
        arrivalTime: "4 min",
        color: "bg-orange-500",
        route: [
            { stop: "Nehru Place", visited: true },
            { stop: "Kalkaji Mandir", visited: true },
            { stop: "Govindpuri", visited: false },
            { stop: "Okhla", visited: false },
            { stop: "Jasola", visited: false },
        ],
        routeProgress: 40,
        reviews: [
            { rating: 4, comment: "Convenient for daily commute" },
            { rating: 3, comment: "Can be crowded at times" },
        ],
    },
    {
        id: 7,
        number: "DTC 703",
        fare: 30,
        crowdLevel: "High",
        fullness: 85,
        arrivalTime: "2 min",
        color: "bg-pink-500",
        route: [
            { stop: "Saket", visited: true },
            { stop: "Malviya Nagar", visited: true },
            { stop: "Hauz Khas", visited: false },
            { stop: "Green Park", visited: false },
            { stop: "AIIMS", visited: false },
        ],
        routeProgress: 40,
        reviews: [
            { rating: 3, comment: "Often crowded but punctual" },
            { rating: 2, comment: "Needs better frequency" },
        ],
    },
    {
        id: 8,
        number: "DTC 804",
        fare: 25,
        crowdLevel: "Low",
        fullness: 45,
        arrivalTime: "5 min",
        color: "bg-teal-500",
        route: [
            { stop: "Dwarka", visited: true },
            { stop: "Palam", visited: true },
            { stop: "Delhi Cantt", visited: false },
            { stop: "Naraina", visited: false },
            { stop: "Rajouri Garden", visited: false },
        ],
        routeProgress: 40,
        reviews: [
            { rating: 5, comment: "Comfortable and timely" },
            { rating: 4, comment: "Good service" },
        ],
    },
    {
        id: 9,
        number: "DTC 905",
        fare: 32,
        crowdLevel: "Medium",
        fullness: 70,
        arrivalTime: "3 min",
        color: "bg-cyan-500",
        route: [
            { stop: "Rohini", visited: true },
            { stop: "Pitampura", visited: true },
            { stop: "Shalimar Bagh", visited: false },
            { stop: "Model Town", visited: false },
            { stop: "Kashmere Gate", visited: false },
        ],
        routeProgress: 40,
        reviews: [
            { rating: 4, comment: "Good connectivity" },
            { rating: 3, comment: "Can be crowded during peak hours" },
        ],
    },
    {
        id: 10,
        number: "DTC 1001",
        fare: 27,
        crowdLevel: "Low",
        fullness: 55,
        arrivalTime: "6 min",
        color: "bg-lime-500",
        route: [
            { stop: "Janakpuri", visited: true },
            { stop: "Tilak Nagar", visited: true },
            { stop: "Subhash Nagar", visited: false },
            { stop: "Rajouri Garden", visited: false },
            { stop: "Shadipur", visited: false },
        ],
        routeProgress: 40,
        reviews: [
            { rating: 5, comment: "Comfortable and clean" },
            { rating: 4, comment: "Good service" },
        ],
    },
];